# This file is part of the RBVMS application.
#
# RBVMSis free software; you can redistribute it and/or modify it under the
# terms of the BSD-3 license. We welcome feedback and contributions, see file
# CONTRIBUTING.md for details.

#-------------------------------------------------------------------------------
# Add Files
#-------------------------------------------------------------------------------
set(SOURCES
    rbvms.cpp
    formulation.cpp
    integrator.cpp)

set(HEADERS
    formulation.hpp
    integrator.hpp)

#-------------------------------------------------------------------------------
# Build executable
#-------------------------------------------------------------------------------
include_directories(../util)

if (MFEM_USE_CUDA)
   enable_language(CUDA)
   set_source_files_properties(${SOURCES} PROPERTIES LANGUAGE CUDA)
endif()

add_executable(rbvms  ${SOURCES} ${HEADERS})
target_link_libraries(rbvms PRIVATE ${LIBRARIES} util ${CMAKE_DL_LIBS})
install(TARGETS rbvms DESTINATION bin)
