// Autogenerated using buildInfo.sh
#include <sstream>
std::istringstream buildInfo(R"(
  Build machine
    host    tudell
    date    2025-03-04
  RBVMS
    dir     /home/ido/data/rbvms-ls2/rbvms-ls
    repo    git@github.com:IdoAkkerman/rbvms.git
    branch  level-set
    commit  9d32e1cf0250fc4748b8096cc1580734942fc445
    changes ## level-set
 M ../CMakeLists.txt
?? ./
  HYPRE
    dir     /home/ido/data/rbvms-ls2/hypre
    repo    https://github.com/hypre-space/hypre.git
    branch  HEAD
    commit  3caa81955eb8d1b4e35d9b450e27cf6d07b50f6e
    changes ## HEAD (no branch)
  MFEM
    dir     /home/ido/data/rbvms-ls2/mfem
    repo    https://github.com/IdoAkkerman/mfem.git
    branch  HEAD
    commit  2db3c8b29d43dbb1bf25876f8e0f6277595d9376
    changes ## HEAD (no branch)
)");
